### ISSUE TITLE
Is there a way to add "read more" kind of text and links under the features in home page?

### ISSUE THREAD

**Issue by erbill** [Evavic44/adocs#3]

**Comment by Evavic44** [comment]
Hey, @erbill sure you can. Vitepress is markdown so it also supports `HTML` code.

In the `index.md`, at the bottom of the layout, you can add a simple markup like this.

```html
<div class="read-more">
  <h1>Read More</h1>
  <p>Click the link below to read more</p>
  <button class="btn">Read More</button>
</div>
```

And style the `read-more` class from within the `docs\.vitepress\theme\custom.css` file

Here's a simple example I just did.

```css
.read-more {
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  gap: 1rem;
  margin-top: 4rem;
}

.read-more h1 {
  font-size: 2.2rem;
  font-weight: 600;
}

.read-more .btn {
  border: 1px solid var(--vp-c-brand-darker);
  color: white;
  border-radius: 10px;
  padding: 0.4rem 1.4rem;
}
```

And this is the output.

![read more example](https://user-images.githubusercontent.com/62628408/230208128-4192f944-5020-4d36-9a99-9769329eccc3.png)

Of course, you have to be careful of your class names to avoid overwriting built-in classes on the vitepress theme. A good example of classes to avoid is the `container`.

Hope this helps. :)
